# This is a basic workflow to help you get started with Actions

name: Snapshot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ public ]
  pull_request:
    branches: [ public ]

  workflow_dispatch:

jobs:
  
  screenshot:
    
    name: Screenshot
    
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        page: ['',gemeinsam, projekte, veranstaltungen, frage-dein-quartier, anmelden, anmerkungen, nachrichten-archive, quartiersplattform, neues-modul-im-kreislauf]
        # page: [gemeinsam]
        # width: [1200, 420]
        width: [420, 1200]
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    
    
    steps:

    - name: Screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        # source: https://arrenberg.app
        source: https://arrenberg.app/${{ matrix.page }}
        #destination: screenshot-${{ matrix.os }}.png
        destination: arrenberg.app-${{ matrix.page }}-${{ matrix.width }}.jpeg
        type: 'jpeg'
        scaleFactor: 1
        # width: 1200
        full-page: true
        width: ${{ matrix.width }}
        path: ./ 

  bundle:
    name: bundle
    needs: screenshot
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/download-artifact@v2
      with:
        path: snapshots
        
    - name: Display structure of downloaded files $before$
      run: ls -R
      
    - name: move artifacts
      run: mv snapshots/*/*.jpeg snapshots/
      
    - name: delete folders  
      run: rm -r snapshots/*/
    
    - run: mkdir -p snapshots/mobil
    - run: mkdir -p snapshots/desktop
    
    - run: mv snapshots/*-1200.jpeg snapshots/desktop/
    - run: mv snapshots/*-420.jpeg snapshots/mobil/
    
    - name: Display structure of downloaded files
      run: ls -R

    
    - name: 'Tar files'
      run: tar -cvf snapshots.tar snapshots

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: Snapshots
        path: snapshots.tar
